name: Java CI with Maven

env:
    JAVA_VERSION: '17'
    DISTRIBUTION: 'adopt'
    LOG_LEVEL: 'warn'
on:
    pull_request:
        branches:
            - develop
jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: ${{ env.JAVA_VERSION }}
                    distribution: ${{ env.DISTRIBUTION }}
            -   name: Compile and Package Project Using Maven
                run: mvn -B -Dorg.slf4j.simpleLogger.defaultLogLevel=${{ env.LOG_LEVEL }} package -DskipTests --file pom.xml
            -   name: Run Unit Tests with Maven
                run: mvn test
