name: Java CI with Maven

on:
    pull_request:
        branches:
            - develop
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'adopt'
            -   name: Build with Maven
                run: mvn -q -B package -DskipTests --file pom.xml
            -   name: Test with Maven
                run: mvn test
