name: Java CI with Maven

env:
    JAVA_VERSION: '17'
    DISTRIBUTION: 'adopt'
    LOG_LEVEL: 'warn'

on:
    pull_request:
        branches:
            - develop
jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup JDK
                uses: actions/setup-java@v3
                with:
                    java-version: ${{ env.JAVA_VERSION }}
                    distribution: ${{ env.DISTRIBUTION }}

            -   name: Archive workspace
                uses: actions/upload-artifact@v3
                with:
                    name: repo
                    path: .

    build:
        needs: prepare
        runs-on: ubuntu-latest
        steps:
            -   name: Download workspace
                uses: actions/download-artifact@v3
                with:
                    name: repo

            -   name: Setup JDK
                uses: actions/setup-java@v3
                with:
                    java-version: ${{ env.JAVA_VERSION }}
                    distribution: ${{ env.DISTRIBUTION }}

            -   name: Build with Maven
                run: mvn -B -Dorg.slf4j.simpleLogger.defaultLogLevel=${{ env.LOG_LEVEL }} package -DskipTests --file pom.xml

            -   name: Cache Maven packages
                uses: actions/cache@v3
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2

            -   name: Build with Maven
                run: mvn -B -Dorg.slf4j.simpleLogger.defaultLogLevel=${{ env.LOG_LEVEL }} package -DskipTests

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   name: Download artifacts
                uses: actions/download-artifact@v3
                with:
                    name: build-artifacts
                    path: target/

            -   name: Setup JDK
                uses: actions/setup-java@v3
                with:
                    java-version: ${{ env.JAVA_VERSION }}
                    distribution: ${{ env.DISTRIBUTION }}

            -   name: Cache Maven packages
                uses: actions/cache@v3
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2

            -   name: Test with Maven
                run: mvn test